services:
  - type: web
    name: masih-almustanadat-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DOCIQ_DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: API_BASE_URL
        value: "https://masih-almustanadat-api.onrender.com"
